#!/usr/bin/env python3
"""
Batch runner for the Small Business Prompt Pack.

Reads prompts.csv, substitutes your business context into every prompt of a
category, and produces either a printable prompt sheet (default) or real AI
drafts when you supply an API key.

Usage
-----
    # See the assembled prompts without spending anything:
    python3 batch_runner.py --category Email --dry-run

    # Generate drafts (needs an API key in the environment):
    export OPENAI_API_KEY=sk-...
    python3 batch_runner.py --category "Sales & Outreach" --context context.txt

    # Everything, one category at a time:
    python3 batch_runner.py --all --context context.txt --out drafts.md

Requires: pip install requests   (only for live generation; dry-run needs nothing)
"""

import argparse
import csv
import json
import os
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROMPTS_FILE = HERE / "prompts.csv"

# Matches [SQUARE BRACKETS] but not markdown links like [text](url).
PLACEHOLDER_RE = re.compile(r"\[([A-Z][A-Z0-9 /:_\-]+)\]")


def load_prompts(path: Path) -> list[dict]:
    """Read the pack and return rows as dicts, skipping blank lines."""
    if not path.exists():
        sys.exit(f"error: cannot find {path.name} next to this script")
    with path.open(newline="", encoding="utf-8") as f:
        rows = [r for r in csv.DictReader(f) if r.get("Prompt")]
    if not rows:
        sys.exit(f"error: {path.name} has no readable prompt rows")
    return rows


def parse_context(path: Path | None) -> dict[str, str]:
    """Parse KEY: value lines into a substitution map. Missing file is fine."""
    if not path:
        return {}
    if not path.exists():
        sys.exit(f"error: context file {path} not found")
    ctx: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, sep, value = line.partition(":")
        if sep and key.strip():
            ctx[key.strip().upper()] = value.strip()
    return ctx


def fill(prompt: str, ctx: dict[str, str]) -> tuple[str, list[str]]:
    """Substitute known variables; report the brackets still unfilled."""
    leftover: list[str] = []

    def repl(m: re.Match) -> str:
        key = m.group(1).strip()
        if key in ctx:
            return ctx[key]
        leftover.append(key)
        return m.group(0)

    return PLACEHOLDER_RE.sub(repl, prompt), sorted(set(leftover))


def build_messages(row: dict, filled: str) -> list[dict]:
    """System + user messages that keep the answer structured and short."""
    system = (
        "You are a practical business writing assistant. Follow the instructions in "
        "the prompt exactly, including any length or format limits. Write in plain, "
        "specific language. Never invent statistics, customer names, or quotes; if a "
        "fact is missing, write [ADD FACT: what is needed] in its place."
    )
    user = (
        f"Task: {row['When To Use It']}\n\n"
        f"Instructions:\n{filled}\n\n"
        f"Return the deliverable only. Expected shape: {row['Expected Output']}"
    )
    return [{"role": "system", "content": system}, {"role": "user", "content": user}]


def generate(messages: list[dict], model: str, api_key: str) -> str:
    """Call an OpenAI-compatible chat endpoint; raise on any API error."""
    import requests  # imported lazily so --dry-run needs no dependencies

    base = os.environ.get("OPENAI_BASE_URL", "https://api.openai.com/v1").rstrip("/")
    resp = requests.post(
        f"{base}/chat/completions",
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
        json={"model": model, "messages": messages, "temperature": 0.7},
        timeout=120,
    )
    resp.raise_for_status()
    return resp.json()["choices"][0]["message"]["content"].strip()


def render_markdown(results: list[dict], category: str, model_note: str) -> str:
    """Turn run results into a skimmable markdown document."""
    lines = [f"# Drafts — {category}", "", f"_Generated by {model_note}_", ""]
    for i, r in enumerate(results, 1):
        lines += [f"## {i}. {r['when']}", "", "**Prompt used**", "", "> " + r["filled"].replace("\n", "\n> "), ""]
        if r.get("leftover"):
            lines += ["**Still needs your input:** " + ", ".join(f"`{x}`" for x in r["leftover"]), ""]
        if r.get("output"):
            lines += ["**Output**", "", r["output"], ""]
        if r.get("error"):
            lines += [f"⚠️ Generation failed: {r['error']}", ""]
        lines += ["---", ""]
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description="Run prompt-pack categories in bulk.")
    ap.add_argument("--category", help="exact category name, e.g. 'Sales & Outreach'")
    ap.add_argument("--all", action="store_true", help="run every category")
    ap.add_argument("--limit", type=int, default=0, help="max prompts per category")
    ap.add_argument("--context", type=Path, help="KEY: value file to fill the brackets")
    ap.add_argument("--out", type=Path, default=None, help="output .md path (default: stdout)")
    ap.add_argument("--model", default=os.environ.get("PROMPT_PACK_MODEL", "gpt-4o-mini"))
    ap.add_argument("--dry-run", action="store_true", help="print prompts, call no API")
    args = ap.parse_args()

    rows = load_prompts(PROMPTS_FILE)
    categories = sorted({r["Category"] for r in rows})

    if not args.all and not args.category:
        print("Available categories:\n  " + "\n  ".join(categories))
        sys.exit("\nPick one with --category, or pass --all. Add --dry-run to preview.")
    if args.category and args.category not in categories:
        sys.exit(f"error: unknown category {args.category!r}\nTry one of: {', '.join(categories)}")

    selected = [r for r in rows if args.all or r["Category"] == args.category]
    ctx = parse_context(args.context)
    api_key = os.environ.get("OPENAI_API_KEY", "").strip()

    if not args.dry_run and not api_key:
        print("warning: no OPENAI_API_KEY set — falling back to --dry-run", file=sys.stderr)
        args.dry_run = True

    grouped: dict[str, list[dict]] = {}
    for row in selected:
        cat = row["Category"]
        if args.limit and len(grouped.get(cat, [])) >= args.limit:
            continue
        filled, leftover = fill(row["Prompt"], ctx)
        item = {"when": row["When To Use It"], "filled": filled, "leftover": leftover}
        if not args.dry_run:
            try:
                item["output"] = generate(build_messages(row, filled), args.model, api_key)
            except Exception as exc:  # keep going; one bad call shouldn't kill the run
                item["error"] = str(exc)
        grouped.setdefault(cat, []).append(item)
        print(f"  [{'ok' if item.get('output') else 'queued'}] {cat}: {row['When To Use It'][:52]}",
              file=sys.stderr)

    note = "dry run (no API calls)" if args.dry_run else args.model
    doc = "\n\n".join(render_markdown(items, cat, note) for cat, items in grouped.items())

    if args.out:
        args.out.write_text(doc, encoding="utf-8")
        total = sum(len(v) for v in grouped.values())
        print(f"wrote {total} prompts to {args.out}")
        if not args.dry_run:
            print(f"estimated tokens: ~{len(json.dumps(doc)) // 4}")
    else:
        print(doc)


if __name__ == "__main__":
    main()
